font_family      Hack Nerd Font
font_size        12.0
modify_font      cell_height 112%

cursor_shape            block
cursor_blink_interval   0

hide_window_decorations titlebar-only
window_padding_width    10 14
macos_option_as_alt     yes
scrollback_lines        -1
copy_on_select          clipboard
confirm_os_window_close 0
enable_audio_bell       no

background_opacity      0.70
background_blur         13

background            #000000
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #000000
selection_background  #303030
selection_foreground  #ffffff
url_color             #d8d8d8

active_border_color   #ffffff
inactive_border_color #262626
active_tab_background   #000000
active_tab_foreground   #ffffff
inactive_tab_background #000000
inactive_tab_foreground #5a5a5a

color0  #000000
color1  #ffffff
color2  #c8c8c8
color3  #a8a8a8
color4  #888888
color5  #d8d8d8
color6  #b8b8b8
color7  #e0e0e0
color8  #5a5a5a
color9  #ffffff
color10 #e8e8e8
color11 #e8e8e8
color12 #a0a0a0
color13 #f0f0f0
color14 #d8d8d8
color15 #ffffff
