local p = require("monopink.palette")
local c = p[vim.o.background == "light" and "light" or "dark"]

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "monopink"
vim.o.termguicolors = true

local function hl(group, spec) vim.api.nvim_set_hl(0, group, spec) end

local groups = {
  Normal       = { fg = c.fg1, bg = c.bg },
  NormalFloat  = { fg = c.fg1, bg = c.bg1 },
  FloatBorder  = { fg = c.bg3, bg = c.bg1 },
  FloatTitle   = { fg = c.em, bg = c.bg1, bold = true },
  Cursor       = { fg = c.bg, bg = c.em },
  CursorLine   = { bg = c.bg2 },
  CursorLineNr = { fg = c.em, bold = true },
  LineNr       = { fg = c.fg3 },
  SignColumn   = { bg = c.bg },
  ColorColumn  = { bg = c.bg1 },
  VertSplit    = { fg = c.bg3 },
  WinSeparator = { fg = c.bg3 },
  Folded       = { fg = c.fg2, bg = c.bg1 },
  FoldColumn   = { fg = c.fg3 },
  Visual       = { bg = c.bg3 },
  Search       = { fg = c.bg, bg = c.alt },
  IncSearch    = { fg = c.bg, bg = c.em },
  CurSearch    = { fg = c.bg, bg = c.em },
  MatchParen   = { fg = c.em, bold = true, underline = true },
  NonText      = { fg = c.fg3 },
  Whitespace   = { fg = c.bg3 },
  SpecialKey   = { fg = c.fg3 },
  Directory    = { fg = c.fg, bold = true },
  Title        = { fg = c.em, bold = true },
  Question     = { fg = c.alt },
  MoreMsg      = { fg = c.alt },
  ModeMsg      = { fg = c.fg, bold = true },
  ErrorMsg     = { fg = c.em, bold = true },
  WarningMsg   = { fg = c.em },
  Conceal      = { fg = c.fg2 },
  StatusLine   = { fg = c.fg1, bg = c.bg1 },
  StatusLineNC = { fg = c.fg3, bg = c.bg },
  WinBar       = { fg = c.fg2, bg = c.bg },
  WinBarNC     = { fg = c.fg3, bg = c.bg },
  Pmenu        = { fg = c.fg1, bg = c.bg1 },
  PmenuSel     = { fg = c.bg, bg = c.em, bold = true },
  PmenuSbar    = { bg = c.bg1 },
  PmenuThumb   = { bg = c.bg3 },
  TabLine      = { fg = c.fg3, bg = c.bg },
  TabLineSel   = { fg = c.em, bg = c.bg, bold = true },
  TabLineFill  = { bg = c.bg },
  QuickFixLine = { bg = c.bg2, bold = true },

  Comment    = { fg = c.fg2, italic = true },
  Constant   = { fg = c.fg1 },
  String     = { fg = c.alt },
  Character  = { fg = c.alt },
  Number     = { fg = c.fg },
  Boolean    = { fg = c.fg, bold = true },
  Float      = { fg = c.fg },
  Identifier = { fg = c.fg1 },
  Function   = { fg = c.fg, bold = true },
  Statement  = { fg = c.em },
  Conditional= { fg = c.em },
  Repeat     = { fg = c.em },
  Label      = { fg = c.em },
  Operator   = { fg = c.fg2 },
  Keyword    = { fg = c.em },
  Exception  = { fg = c.em },
  PreProc    = { fg = c.emd },
  Include    = { fg = c.em },
  Define     = { fg = c.em },
  Macro      = { fg = c.emd },
  Type       = { fg = c.fg, bold = true },
  StorageClass = { fg = c.em },
  Structure  = { fg = c.fg, bold = true },
  Typedef    = { fg = c.fg, bold = true },
  Special    = { fg = c.emd },
  Delimiter  = { fg = c.fg2 },
  Underlined = { fg = c.alt, underline = true },
  Todo       = { fg = c.bg, bg = c.em, bold = true },
  Error      = { fg = c.em, bold = true },

  ["@variable"]            = { fg = c.fg1 },
  ["@variable.builtin"]    = { fg = c.emd },
  ["@variable.parameter"]  = { fg = c.fg1, italic = true },
  ["@variable.member"]     = { fg = c.fg1 },
  ["@constant"]            = { fg = c.fg },
  ["@constant.builtin"]    = { fg = c.fg, bold = true },
  ["@module"]              = { fg = c.fg1 },
  ["@string"]              = { fg = c.alt },
  ["@string.escape"]       = { fg = c.altd, bold = true },
  ["@string.special"]      = { fg = c.altd },
  ["@character"]           = { fg = c.alt },
  ["@function"]            = { fg = c.fg, bold = true },
  ["@function.builtin"]    = { fg = c.fg, bold = true },
  ["@function.call"]       = { fg = c.fg },
  ["@function.method"]     = { fg = c.fg, bold = true },
  ["@constructor"]         = { fg = c.fg, bold = true },
  ["@keyword"]             = { fg = c.em },
  ["@keyword.function"]    = { fg = c.em },
  ["@keyword.operator"]    = { fg = c.em },
  ["@keyword.return"]      = { fg = c.em, bold = true },
  ["@keyword.import"]      = { fg = c.em },
  ["@type"]                = { fg = c.fg, bold = true },
  ["@type.builtin"]        = { fg = c.fg1, bold = true },
  ["@attribute"]           = { fg = c.emd },
  ["@property"]            = { fg = c.fg1 },
  ["@operator"]            = { fg = c.fg2 },
  ["@punctuation"]         = { fg = c.fg2 },
  ["@punctuation.bracket"] = { fg = c.fg2 },
  ["@punctuation.special"] = { fg = c.emd },
  ["@comment"]             = { fg = c.fg2, italic = true },
  ["@comment.todo"]        = { fg = c.bg, bg = c.em, bold = true },
  ["@comment.note"]        = { fg = c.bg, bg = c.alt, bold = true },
  ["@comment.warning"]     = { fg = c.bg, bg = c.emd, bold = true },
  ["@comment.error"]       = { fg = c.bg, bg = c.em, bold = true },
  ["@tag"]                 = { fg = c.em },
  ["@tag.attribute"]       = { fg = c.fg1, italic = true },
  ["@tag.delimiter"]       = { fg = c.fg2 },
  ["@markup.heading"]      = { fg = c.em, bold = true },
  ["@markup.strong"]       = { fg = c.fg, bold = true },
  ["@markup.italic"]       = { fg = c.fg1, italic = true },
  ["@markup.link"]         = { fg = c.alt, underline = true },
  ["@markup.link.url"]     = { fg = c.altd, underline = true },
  ["@markup.raw"]          = { fg = c.alt },
  ["@markup.list"]         = { fg = c.em },
  ["@markup.quote"]        = { fg = c.fg2, italic = true },
  ["@diff.plus"]           = { fg = c.alt },
  ["@diff.minus"]          = { fg = c.em },

  DiagnosticError = { fg = c.em },
  DiagnosticWarn  = { fg = c.fg1 },
  DiagnosticInfo  = { fg = c.fg2 },
  DiagnosticHint  = { fg = c.alt },
  DiagnosticOk    = { fg = c.alt },
  DiagnosticUnderlineError = { undercurl = true, sp = c.em },
  DiagnosticUnderlineWarn  = { undercurl = true, sp = c.fg2 },
  DiagnosticUnderlineInfo  = { undercurl = true, sp = c.fg3 },
  DiagnosticUnderlineHint  = { undercurl = true, sp = c.alt },
  DiagnosticVirtualTextError = { fg = c.emd, bg = c.bg1 },
  DiagnosticVirtualTextWarn  = { fg = c.fg2, bg = c.bg1 },
  DiagnosticVirtualTextInfo  = { fg = c.fg3, bg = c.bg1 },
  DiagnosticVirtualTextHint  = { fg = c.altd, bg = c.bg1 },

  LspReferenceText  = { bg = c.bg2 },
  LspReferenceRead  = { bg = c.bg2 },
  LspReferenceWrite = { bg = c.bg2, underline = true },
  LspInlayHint      = { fg = c.fg3, bg = c.bg1, italic = true },
  LspSignatureActiveParameter = { fg = c.em, bold = true },

  DiffAdd    = { fg = c.alt, bg = c.bg1 },
  DiffChange = { fg = c.fg1,  bg = c.bg1 },
  DiffDelete = { fg = c.em, bg = c.bg1 },
  DiffText   = { fg = c.fg,   bg = c.bg2, bold = true },
  Added      = { fg = c.alt },
  Changed    = { fg = c.fg1 },
  Removed    = { fg = c.em },
  GitSignsAdd    = { fg = c.altd },
  GitSignsChange = { fg = c.fg2 },
  GitSignsDelete = { fg = c.emd },

  TelescopeNormal       = { fg = c.fg1, bg = c.bg1 },
  TelescopeBorder       = { fg = c.bg3, bg = c.bg1 },
  TelescopeTitle        = { fg = c.em, bold = true },
  TelescopeSelection    = { fg = c.fg, bg = c.bg3, bold = true },
  TelescopeMatching     = { fg = c.em, bold = true },
  TelescopePromptPrefix = { fg = c.em },

  SnacksPickerDir       = { fg = c.fg2 },
  SnacksPickerMatch     = { fg = c.em, bold = true },
  SnacksPickerSelected  = { fg = c.fg, bg = c.bg3 },
  SnacksNotifierInfo    = { fg = c.alt },
  SnacksNotifierError   = { fg = c.em },
  SnacksDashboardHeader = { fg = c.em, bold = true },
  SnacksDashboardIcon   = { fg = c.alt },
  SnacksDashboardDesc   = { fg = c.fg1 },
  SnacksDashboardKey    = { fg = c.em },
  SnacksIndent          = { fg = c.bg3 },
  SnacksIndentScope     = { fg = c.emd },

  NeoTreeNormal       = { fg = c.fg1, bg = c.bg },
  NeoTreeNormalNC     = { fg = c.fg2, bg = c.bg },
  NeoTreeDirectoryName= { fg = c.fg1 },
  NeoTreeDirectoryIcon= { fg = c.fg2 },
  NeoTreeRootName     = { fg = c.em, bold = true },
  NeoTreeGitAdded     = { fg = c.alt },
  NeoTreeGitDeleted   = { fg = c.em },
  NeoTreeGitModified  = { fg = c.fg1 },
  NeoTreeIndentMarker = { fg = c.bg3 },

  CmpItemAbbrMatch      = { fg = c.em, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = c.em },
  CmpItemKind           = { fg = c.fg2 },
  CmpItemMenu           = { fg = c.fg3 },
  BlinkCmpLabelMatch    = { fg = c.em, bold = true },
  BlinkCmpMenuSelection = { fg = c.bg, bg = c.em },
  BlinkCmpKind          = { fg = c.fg2 },

  WhichKey          = { fg = c.em },
  WhichKeyGroup     = { fg = c.fg1 },
  WhichKeyDesc      = { fg = c.fg1 },
  WhichKeySeparator = { fg = c.fg3 },
  WhichKeyFloat     = { bg = c.bg1 },

  NoiceCmdlinePopupBorder = { fg = c.bg3 },
  NoiceCmdlineIcon        = { fg = c.em },

  IblIndent = { fg = c.bg3 },
  IblScope  = { fg = c.emd },

  texCmd            = { fg = c.em },
  texCmdEnv         = { fg = c.em, bold = true },
  texEnvArgName     = { fg = c.alt },
  texMathZone       = { fg = c.fg },
  texMathZoneEnv    = { fg = c.fg },
  texMathDelim      = { fg = c.emd },
  texMathOper       = { fg = c.fg2 },
  texCmdMath        = { fg = c.em },
  texFileArg        = { fg = c.alt },
  texTitleArg       = { fg = c.fg, bold = true },
  texSectionArg     = { fg = c.fg, bold = true },
  texCmdPart        = { fg = c.em, bold = true },
  texCmdSection     = { fg = c.em, bold = true },
  texRefArg         = { fg = c.alt, underline = true },
  texComment        = { fg = c.fg2, italic = true },

  RenderMarkdownH1Bg = { fg = c.em, bold = true },
  RenderMarkdownH2Bg = { fg = c.fg, bold = true },
  RenderMarkdownCode = { bg = c.bg1 },
  RenderMarkdownBullet = { fg = c.em },
}

for group, spec in pairs(groups) do hl(group, spec) end

local t = {
  c.bg, c.em, c.alt, c.fg1, c.fg2, c.em, c.alt, c.fg,
  c.fg3, c.em, c.alt, c.fg1, c.fg2, c.em, c.alt, c.fg,
}
for i, col in ipairs(t) do vim.g["terminal_color_" .. (i - 1)] = col end
