#!/usr/bin/env sh

SCRIPTS="$HOME/.config/yabai/scripts"

yabai -m config focus_follows_mouse          autofocus
yabai -m config mouse_follows_focus          on
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp

yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50

yabai -m config auto_balance                 off

yabai -m config window_shadow                on
yabai -m config window_opacity               off

yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

"$SCRIPTS/adapt-display.sh" >/dev/null 2>&1 &

yabai -m rule --add app="^System Settings$"   manage=off
yabai -m rule --add app="^Calculator$"        manage=off
yabai -m rule --add app="^Archive Utility$"   manage=off
yabai -m rule --add app="^Activity Monitor$"  manage=off
yabai -m rule --add app="^Finder$" title="^(Copy|Move|Info|Connect)" manage=off
yabai -m rule --add app="^Übersicht$"         manage=off sticky=on

yabai -m signal --add event=space_created    action="$SCRIPTS/adapt-display.sh >/dev/null 2>&1 &"

yabai -m signal --add event=display_added    action="$SCRIPTS/adapt-display.sh >/dev/null 2>&1 &"
yabai -m signal --add event=display_removed  action="$SCRIPTS/adapt-display.sh >/dev/null 2>&1 &"
yabai -m signal --add event=display_resized  action="$SCRIPTS/adapt-display.sh >/dev/null 2>&1 &"
yabai -m signal --add event=display_moved    action="$SCRIPTS/adapt-display.sh >/dev/null 2>&1 &"

echo "yabai config loaded"
